# Generated by Django 4.2.13 on 2024-07-07 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0002_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='refs.series')),
            ],
        ),
    ]
