# Generated by Django 4.2.13 on 2024-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0004_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_img',
            field=models.ImageField(upload_to='author_image', verbose_name='Фото/портрет автора'),
            preserve_default=False,
        ),
    ]
