# Generated by Django 4.2.13 on 2024-07-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0006_alter_author_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to='author_image', verbose_name='Фото/портрет автора'),
        ),
    ]
