# Generated by Django 4.2.13 on 2024-07-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0007_alter_author_author_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_img',
        ),
    ]
