# Generated by Django 4.2.13 on 2024-07-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0004_publisher'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('cover', models.ImageField(upload_to='book_covers/%Y/%m/%d/', verbose_name='Обложка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='refs.author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='refs.genre', verbose_name='Жанр')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publisher', to='refs.publisher', verbose_name='Издательство')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='refs.series', verbose_name='Серия')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
