# Generated by Django 4.2.13 on 2024-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_book_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
