# Generated by Django 4.2.13 on 2024-08-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0004_publisher'),
        ('goods', '0003_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='refs.genre', verbose_name='Жанр'),
        ),
    ]
