# Generated by Django 4.2.13 on 2024-08-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0016_alter_customerprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='code',
            field=models.CharField(blank=True, choices=[('33', '33'), ('29', '29'), ('25', '25')], max_length=2, null=True, verbose_name='Код мобильного оператора'),
        ),
    ]
