# Generated by Django 4.2.13 on 2024-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.BigIntegerField(default=23, verbose_name='ma'),
            preserve_default=False,
        ),
    ]
