# Generated by Django 4.2.13 on 2024-08-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_book_description'),
        ('orders', '0002_cart_created_cart_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.cart', verbose_name='Корзина')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_in_cart', to='goods.book', verbose_name='Книга')),
            ],
        ),
    ]
