# Generated by Django 4.2.13 on 2024-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='orders.cart')),
            ],
        ),
    ]
